language: ruby
bundler_args: --full-index --without development
cache: bundler
rvm:
  - 2.2.3
env:
  global:
    - DISPLAY=":99.0
  matrix:
    - TEST_LOCALE=fra
    - TEST_LOCALE=eng
before_install: test/ci/before_install
before_script:  test/ci/before_script
script: xvfb-run -a bundle exec rake test:run_all DRIVER=webkit LOCALE=$TEST_LOCALE
# script: bundle exec rake test:core
services:
  - redis-server